### ISSUE TITLE
C# 8 is not fully supported on .netcoreapp2.1

### ISSUE THREAD

**Issue by andreasohlund** [Particular/TimeoutMigrationTool#107]
We're using C# 8 in the tool but as long as we target .netcoreapp2.1 this is dangerous since its not fully supported

https://stackoverflow.com/a/57020770/236004

We should either go back to `7.3` (which is the default that `Particular.Packaging` sets) or update the TFC to .netcoreapp3.1

**Comment by WilliamBZA** [comment]
We're targeting netcoreapp3.1 now, closing.
