### ISSUE TITLE
RabbitMQ message loss when time to be sent is in the past

### ISSUE THREAD

**Issue by lancekeas** [Particular/TimeoutMigrationTool#258]
Processing a timeout message with a delay in seconds = 0, RabbitStagePump will set rabbit message expiration = 0.  This message is sent to exchange 'nsb.delay-level-00' and due to the exchange binding, the message will get routed directly to its final destination queue (not one of the delay infrastructure queues).  Since the message has an expiration of 0 milliseconds, rabbit can deadletter the message and it never gets processed by the intended nsb handler.

**Comment by bording** [comment]
Hi @lancekeas,

It does look like the TimeoutMigrationTool is incorrectly using the message expiration property. 

We have prioritized your issue and we will be working on it as of now to release the fix as soon as we can.

**Comment by bording** [comment]
@lancekeas Particular.TimeoutMigration 1.2.1 includes the fix for the bug you reported and has been released. Thanks for the report!

**Comment by lancekeas** [comment]
Tested and working as expected.  Thank you!
