### ISSUE TITLE
Timeouts are delivered early when migrating to RabbitMQ

### ISSUE THREAD

**Issue by lancekeas** [Particular/TimeoutMigrationTool#265]
NOTE: This issue has been edited. See the `Original issue content` section for the original information.

### Symptoms

Migrated timeouts have their expiration time cut in half

### Who's affected

Anyone who used the migration tool to move timeout messages into the RabbitMQ transport's [delayed delivery infrastructure](https://docs.particular.net/transports/rabbitmq/delayed-delivery) is affected.

### Root cause

The tool generates a routing key that is bit-shited one bit to the right which effectively means that the expiration gets divided by two.

### Backported to

- [1.2.2](TBD)

## Investigation

The timeout migration tool is not correctly calculating routing keys when inserting messages into the delayed delivery infrastructure.

The max level calculation is the culprit here. It should be [27](https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/NServiceBus.Transport.RabbitMQ/DelayedDelivery/DelayInfrastructure.cs#L11-L12), but is set to [28](https://github.com/Particular/TimeoutMigrationTool/blob/master/src/TimeoutMigrationTool/RabbitMq/RabbitMqTimeoutTarget.cs#L160) instead.

The maximum delay is also being calculated incorrectly: [Transport](https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/NServiceBus.Transport.RabbitMQ/DelayedDelivery/DelayInfrastructure.cs#L14) vs. [Tool](https://github.com/Particular/TimeoutMigrationTool/blob/master/src/TimeoutMigrationTool/RabbitMq/RabbitMqTimeoutTarget.cs#L158)

Since the maximum level is too high, the routing key has too many total levels in it. For example, for a delay of 3600 seconds, here are the keys
```
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.1.0.0.0.0.1.0.0.0.0.destination (transport)
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.1.0.0.0.0.1.0.0.0.0.destination (tool)
```
There is an extra `0` on the left side of the key, which means that the rightmost level is never used. This effectively means the delay infrastructure sees it as 
```
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.1.0.0.0.0.1.0.0.0.0.destination (transport)
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.1.0.0.0.0.1.0.0.0.destination (tool)
```
You can see that everything has been bit-shifted to the right, so instead of 3600 seconds, you get 1800 seconds.

This will happen for every timeout message migrated to RabbitMQ.

## Original issue content

In my test cases, timeouts are delivered between 40% - 50% early (i.e. if timeout is due in 4 hours it will be delivered in roughly 2 hours).  Issue appears to be with RabbitMqTimeoutTarget.MaxLevel.  Should be 27 vs 28.  

Attached are my test results for reference.  TestName column meaning:

- RabbitNative: timeout messages are sent directly to rabbitmq using nsb rabbitmq transport.  Included for baseline reference.
- MigrationTool: timeout messages are persisted to sql via timeout manager and then migrated to rabbit using migration tool.

[migrationtool-deliverytime-testresults.xlsx](https://github.com/Particular/TimeoutMigrationTool/files/6963658/migrationtool-deliverytime-testresults.xlsx)

**Comment by bording** [comment]
Hi @lancekeas,

It does look like the TimeoutMigrationTool is using an incorrect value for the max level, which results in the routing key being generated with all of the values being shifted one level to the right. This does indeed mean that timeouts will be delivered more quickly than intended.

We have prioritized your issue and we will be working on it as of now to release the fix as soon as we can.

**Comment by andreasohlund** [comment]
@lancekeas we're about to release a fix for this and have updated the issue description with more details. Expect a fix to be released in the next day or so

**Comment by andreasohlund** [comment]
Fix have been released. @lancekeas thanks again for reporting it. Would you be able to confirm that its working as expected?

**Comment by lancekeas** [comment]
Working as expected.  Thanks for the quick response!
