### ISSUE TITLE
RavenDB: Expected to receive 500 timeouts but only found 501

### ISSUE THREAD

**Issue by DavidBoike** [Particular/TimeoutMigrationTool#353]
**This issue was fixed in https://github.com/Particular/TimeoutMigrationTool/pull/327 and is slated to be released in version 1.4.0. As it is a fairly minor bug that was fixed somewhat accidentally, a timeline for this release is not currently planned.**

## Summary

It's possible that when reading timeouts from RavenDB, the following cryptic error can occur:

> Expected to receive 500 timeouts but only found 501

This is due to some [odd behavior in StringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.maxcapacity), in which the StringBuilder can throw an exception for exceeding the MaxCapacity _but still successfully append the string and extend the capacity_:

> In .NET Core and in the .NET Framework 4.0 and later versions, when you instantiate the [StringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=net-6.0) object by calling the [StringBuilder(Int32, Int32)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.-ctor?view=net-6.0#system-text-stringbuilder-ctor(system-int32-system-int32)) constructor, both the length and the capacity of the [StringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=net-6.0) instance can grow beyond the value of its [MaxCapacity](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.maxcapacity?view=net-6.0#system-text-stringbuilder-maxcapacity) property. This can occur particularly when you call the [Append(String)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append?view=net-6.0#system-text-stringbuilder-append(system-string)) and [AppendFormat(String, Object)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.appendformat?view=net-6.0#system-text-stringbuilder-appendformat(system-string-system-object)) methods to append small strings.

The code that then checks to see if we got all the data we expected to get from the server then throws becuase it got **too much**.

## Workaround

Running the tool again will retry the batch that failed, and as the error occurs only occasionally, the migration should proceed correctly from the point where it left off.

**Comment by awright18** [comment]
This fix was included in the 1.3.1 release.
