### ISSUE TITLE
Add support for version 2 of the RabbitMQ delay infrastructure

### ISSUE THREAD

**Issue by andreasohlund** [Particular/TimeoutMigrationTool#441]
As highlighted upgrading RabbitMQ transport to v7.x the tool does not support migrating timeouts to the new v2 delay infrastructure:

- https://github.com/Particular/TimeoutMigrationTool/pull/426 

The tool needs to be updated with an options for users to select the target delay infra version

**Comment by awright18** [comment]
Particular.TimeoutMigration version 2.0.0 use the v2 delay infrastructure by default. See the [documentation ](https://docs.particular.net/nservicebus/tools/migrate-to-native-delivery#tool-options-target-options)for how to use v1 if you need to.
